/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#dce1fb",
        "primary-container": "#10b981",
        "error": "#ffb4ab",
        "on-primary-fixed": "#002113",
        "outline-variant": "#3c4a42",
        "surface-container-highest": "#2e3447",
        "on-tertiary-fixed": "#410004",
        "surface-tint": "#4edea3",
        "surface": "#0c1324",
        "tertiary-fixed": "#ffdad7",
        "outline": "#86948a",
        "secondary-container": "#ee9800",
        "on-primary-fixed-variant": "#005236",
        "surface-container-low": "#151b2d",
        "on-primary-container": "#00422b",
        "on-primary": "#003824",
        "surface-container-high": "#23293c",
        "tertiary-container": "#ff7a73",
        "primary-fixed-dim": "#4edea3",
        "inverse-primary": "#006c49",
        "primary": "#4edea3",
        "tertiary": "#ffb3ad",
        "on-secondary": "#472a00",
        "on-background": "#dce1fb",
        "surface-container": "#191f31",
        "primary-fixed": "#6ffbbe",
        "error-container": "#93000a",
        "surface-bright": "#33394c",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface-variant": "#2e3447",
        "on-tertiary-fixed-variant": "#930013",
        "on-secondary-container": "#5b3800",
        "inverse-on-surface": "#2a3043",
        "secondary": "#ffb95f",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-lowest": "#070d1f",
        "on-secondary-fixed-variant": "#653e00",
        "surface-dim": "#0c1324",
        "on-tertiary-container": "#79000e",
        "on-tertiary": "#68000a",
        "secondary-fixed": "#ffddb8",
        "on-surface-variant": "#bbcabf",
        "background": "#0c1324",
        "on-secondary-fixed": "#2a1700",
        "inverse-surface": "#dce1fb",
        "secondary-fixed-dim": "#ffb95f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "panel-gap": "24px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "unit": "4px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
}
